# Generated by Django 4.2.3 on 2023-07-28 20:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Bio')),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_supervisor', models.BooleanField(default=False)),
                ('is_manager', models.BooleanField(default=False)),
                ('is_dean', models.BooleanField(default=False)),
                ('head_section', models.BooleanField(default=False)),
                ('sub_hedad_section', models.BooleanField(default=False)),
                ('super_teacher', models.BooleanField(default=False)),
                ('teacher', models.BooleanField(default=False)),
                ('tutor', models.BooleanField(default=False)),
                ('dgree', models.CharField(choices=[('PROF', 'professor'), ('DR', 'dector'), ('MR', 'master'), ('BC', 'bachelor')], max_length=4, verbose_name='Dgree')),
                ('finan', models.BooleanField(default=False)),
                ('auditor', models.BooleanField(default=False)),
                ('accountant', models.BooleanField(default=False)),
                ('registerer', models.BooleanField(default=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country_profiles', to='locations.country', verbose_name='Country')),
                ('hquarter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hquarter_profiles', to='offices.hquarter', verbose_name='Hquarter')),
                ('office', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_profiles', to='offices.office', verbose_name='Office')),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region_profiles', to='locations.region', verbose_name='Region')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector_profiles', to='offices.sector', verbose_name='Sector')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_profiles', to='locations.state', verbose_name='State')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
